#pragma once
#include <Arduino.h>

// ── Units enum ────────────────────────────────────────────────────────────────
enum class CaliperUnit : uint8_t { MM = 0, INCH = 1 };

// ── Reading — const fields, construct-only ────────────────────────────────────
struct CaliperReading {
    const int16_t    whole;  // signed integer part
                             //   mm   : e.g. -12  for -12.34 mm
                             //   inch : e.g.   0  for  -0.3395 in
    const uint16_t   frac;   // fractional part (unsigned, sign carried by whole or negative flag)
                             //   mm   : hundredths   0-99   (e.g.  34 for -12.34 mm)
                             //   inch : ten-thousandths 0-9999 (e.g. 3395 for -0.3395 in)
    const bool       negative; // true when value is negative (needed when whole == 0)
    const CaliperUnit unit;
};

// ── Driver ────────────────────────────────────────────────────────────────────
// ISR-driven, ESP32-only.
//
// Protocol (generic Chinese 24-bit caliper):
//   CLK is generated by the caliper.  DATA changes around the rising edge.
//   Each packet consists of 1 sync clock followed by 24 data clocks (25 total).
//   Between packets CLK idles LOW for ~50-90 ms; the long LOW gap before a
//   rising edge is used to detect packet boundaries.
//   Data bits are LSB-first, sampled on the rising edge:
//     bits  0-15 : raw value in 0.01 mm units (unsigned magnitude)
//     bit     20 : sign  (0 = positive, 1 = negative)
//     bit     23 : units (0 = mm,       1 = inch)
//
// Sync detection:
//   The inter-packet gap is a long HIGH on CLK (~50-90 ms).
//   RISING records its timestamp.  FALLING measures the preceding HIGH duration.
//   If HIGH duration >5 ms → inter-packet gap detected; next rising edge resets
//   accumulator and starts a fresh packet (no phantom bit, direct bit mapping).
//
// Usage:
//   DigitalCaliper caliper(CLK_PIN, DATA_PIN);
//   caliper.begin();
//   CaliperReading r;
//   if (caliper.read(r)) { /* use r.whole, r.frac, r.unit */ }
//
class DigitalCaliper {
public:
    DigitalCaliper(uint8_t clk_pin, uint8_t data_pin);

    // Attach interrupts and start receiving.
    void begin();

    // Returns true and fills `out` when a fresh reading has arrived since the
    // last call.  Returns false (and leaves `out` unchanged) if no new data.
    bool read(CaliperReading& out);

private:
    // Single CHANGE ISR — dispatches internally to rising/falling path.
    // (One instance supported per program; promote to array if two calipers needed.)
    static void IRAM_ATTR isr_change();

    static volatile int64_t  s_rise_us;   // timestamp of last rising edge
    static volatile int64_t  s_fall_us;   // timestamp of last falling edge (sync LOW measurement)

    // State machine — only touched by the ISR.
    static volatile uint32_t s_accumulator;  // 24-bit shift register
    static volatile uint8_t  s_bit_idx;      // 0..23

    // Published result — written by RISING ISR, read by loop().
    // `s_ready` is written last (release-style) so loop() sees a consistent pair.
    static volatile int32_t  s_raw_value;   // decoded signed hundredths
    static volatile uint8_t  s_raw_unit;    // 0=mm 1=inch
    static volatile bool     s_ready;       // true = new value waiting

    uint8_t m_clk_pin;
    uint8_t m_data_pin;

    // Static pointer so ISRs (which have no `this`) can reach pin numbers.
    static DigitalCaliper* s_instance;

    // Decode raw 24-bit accumulator → publish to s_raw_* slots.
    static void publish(uint32_t acc);
};
