#pragma once
#include <Arduino.h>

// ── Units enum ────────────────────────────────────────────────────────────────
enum class CaliperUnit : uint8_t { MM = 0, INCH = 1 };

// ── Reading — const fields, construct-only ────────────────────────────────────
struct CaliperReading {
    const int16_t     whole;    // signed integer part
                                //   mm   : e.g. -12  for -12.34 mm
                                //   inch : e.g.   0  for  -0.3395 in
    const uint16_t    frac;     // fractional part (unsigned)
                                //   mm   : hundredths   0-99
                                //   inch : ten-thousandths 0-9999
    const bool        negative; // true when value is negative (needed when whole == 0)
    const CaliperUnit unit;
};

// ── Driver ────────────────────────────────────────────────────────────────────
// ISR-driven, ESP32-only.  Supports up to MAX_INSTANCES concurrent calipers.
//
// Protocol (generic Chinese 24-bit caliper, NPN level-shifter inverts CLK+DATA):
//   CLK is generated by the caliper.  NPN inversion means:
//     Caliper CLK HIGH (idle) → ESP CLK LOW
//     Caliper CLK FALLING     → ESP CLK RISING
//     Caliper CLK RISING (data valid) → ESP CLK FALLING
//   Inter-packet gap appears as a long LOW on ESP CLK (~50-90 ms).
//   Data bits are LSB-first, sampled on the ESP CLK falling edge:
//     bits  0-15 : raw value in 0.01 mm units (unsigned magnitude)
//     bit     20 : sign  (0 = positive, 1 = negative)
//     bit     23 : units (0 = mm,       1 = inch)
//
// Usage:
//   DigitalCaliper caliper(CLK_PIN, DATA_PIN);
//   caliper.begin();
//   CaliperReading r;
//   if (caliper.read(r)) { /* use r.whole, r.frac, r.unit */ }
//
class DigitalCaliper {
public:
    static constexpr uint8_t MAX_INSTANCES = 4;

    DigitalCaliper(uint8_t clk_pin, uint8_t data_pin);
    ~DigitalCaliper();

    // Attach interrupt and start receiving.  Claims one of MAX_INSTANCES slots.
    void begin();

    // Returns true and fills `out` when a fresh reading has arrived since the
    // last call.  Returns false (and leaves `out` unchanged) if no new data.
    bool read(CaliperReading& out);

    // Diagnostics — written by the ISR, readable from loop().
    volatile uint32_t packet_count = 0;
    volatile uint8_t  bit_idx      = 0;
    volatile uint32_t accumulator  = 0;

private:
    void IRAM_ATTR isr_handler();
    void           publish(uint32_t acc);

    const uint8_t m_clk_pin;
    const uint8_t m_data_pin;
    uint8_t       m_slot = 0xFF;  // 0xFF = not registered

    volatile int64_t  m_rise_us   = 0;
    volatile int64_t  m_fall_us   = 0;
    volatile int32_t  m_raw_value = 0;
    volatile uint8_t  m_raw_unit  = 0;
    volatile bool     m_ready     = false;

    // Static registry — one entry per supported concurrent instance.
    static DigitalCaliper* s_instances[MAX_INSTANCES];

    // One ISR trampoline per slot — required because attachInterrupt needs a
    // plain function pointer (no closure / no argument).
    static void IRAM_ATTR isr_slot_0();
    static void IRAM_ATTR isr_slot_1();
    static void IRAM_ATTR isr_slot_2();
    static void IRAM_ATTR isr_slot_3();
    static void (*const s_isrs[MAX_INSTANCES])();
};
